Improve markdown2gdrive

diff --git a/bin/markdown2gdrive b/bin/markdown2gdrive
--- a/bin/markdown2gdrive
+++ b/bin/markdown2gdrive
@@ -1,11 +1,19 @@
 #!/bin/zsh
 
-set -euo pipefail
+set -eo pipefail
 IFS=$'\n\t'
 PROGRAM_NAME=$0
 
+red=$'\e[1;31m'
+grn=$'\e[1;32m'
+yel=$'\e[1;33m'
+blu=$'\e[1;34m'
+mag=$'\e[1;35m'
+cyn=$'\e[1;36m'
+end=$'\e[0m'
+
 function usage {
-    echo "Usage: $PROGRAM_NAME [--parent/-p] path"
+    echo "Usage: $PROGRAM_NAME [--parent/-p] [--help/-h] [-t/--testing] path [path...]"
     exit 1
 }
 
@@ -59,38 +67,43 @@ if [ $HELP = true ]; then
     usage
 fi
 
-filename=${OPTIONS[1]:-}
-if [ -z "$filename" ]; then
+if [ -z "$OPTIONS" ]; then
     echo >&2 "Invalid number of argument, need markdown path to be passed"
     usage
 fi
 
-export_filename=$(echo "$(mktemp -d)/${${filename:r}:t}.$FORMAT")
+function convert_and_export () {
+    filename=$1
+    export_filename=$(echo "$(mktemp -d)/${${filename:r}:t}.$FORMAT")
 
-echo "Converting $filename to $export_filename"
-set -x
-pandoc $filename ${PANDOC_OPTIONS[@]} --from markdown --to $FORMAT -o "$export_filename"
-set +x
-[ $? -ne 0 ] && { printf "Conversion failed\n"; rm "$export_filename"; exit 1; }
+    printf "\n${grn}Converting $filename${end}\n"
+    echo "Exporting to $export_filename"
+    set -x
+    pandoc $filename ${PANDOC_OPTIONS[@]} --from markdown --to $FORMAT -o "$export_filename"
+    set +x
+    [ $? -ne 0 ] && { printf "Conversion failed\n"; rm "$export_filename"; exit 1; }
 
-if [ $TESTING = true ]; then
-    open "$export_filename"
-    exit 0
-fi
+    if [ $TESTING = true ]; then
+        open "$export_filename"
+        exit 0
+    fi
 
-ls $export_filename
+    ls $export_filename
 
-if [ -z $PARENT ]; then
-    to_run="gdrive import \"$export_filename\""
-else
-    to_run="gdrive import -p $PARENT \"$export_filename\""
-fi
+    if [ -z $PARENT ]; then
+        to_run="gdrive import \"$export_filename\""
+    else
+        to_run="gdrive import -p $PARENT \"$export_filename\""
+    fi
 
-set -x
-ls $export_filename
-eval $to_run
-set +x
+    set -x
+    ls $export_filename
+    eval $to_run
+    set +x
 
-exit 0
+    rm "$export_filename"
+}
 
-# rm "$export_filename"
+for filename in $OPTIONS; do
+    convert_and_export $filename
+done
