Improve update files

diff --git a/bin/update-software b/bin/update-software
--- a/bin/update-software
+++ b/bin/update-software
@@ -9,6 +9,10 @@ set -e
 if [[ "$OSTYPE" =~ ^darwin ]]; then
     ssh-add -A
 
+    log_info "Updating xcode command line tools"
+    # Fails when it's already installed
+    xcode-select --install  || true
+
     log_info "Updating brew packages"
     brew update
     # NOTE: when using pinned packages, brew upgrade fails
