Improve cheats and snippets

diff --git a/cheatsheets/bash b/cheatsheets/bash
--- a/cheatsheets/bash
+++ b/cheatsheets/bash
@@ -12,6 +12,7 @@ done
 
 # Define default argument in bash script
 ARG1=${1:-foo}
+${LIFE-Happiness}   # defaults to Happiness if $LIFE is unset
 
 # Iterate over a list of things in a text file
 for toaster in $(cat toasters.txt) ; do
@@ -34,14 +35,18 @@ set -o verbose  # set option
 set +o verbose  # unset option
 
 verbose/-v      # display commands
-errexti/-o      # exit on error
-xtrace/-x       # Print a trace of simple commands
+errexit/-e      # exit on error
+xtrace/-x       # print a trace of simple commands
+nounset/-u      # exit if any variable is unset
 
 # tests
 
 ## Regex check
 if [[ "$CURRENT_SHELL" =~ "zsh" ]]; then
 fi
+
+## User id
+[[ $(id -u) -ne 0 ]] && echo "run as root!" && exit 1
 
 ## Check if command exists
 if ! command -v $command &> /dev/null; then
